.\"                                      Hey, EMACS: -*- nroff -*-
.TH GENI-FETCH-AGGMON 1 "March 29, 2016"
.SH NAME
geni-fetch-aggmon \- Fetch status of aggregate managers from GENI monitoring
.SH SYNOPSIS
.B geni-fetch-aggmon
[-h] [-d DEST]
.br
.SH DESCRIPTION
.B geni-fetch-aggmon
fetches aggregate status from the GENI monitoring server.
.B geni-fetch-aggmon
reads the "available" event data to determine whether an aggregate
is available. A JSON file is output, mapping aggregate URNs to either
"up" or "down". The data is written to the destination specified with the
.I \-d
argument.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-d, \-\-dest <DEST>
The name of the output file
.TP
.B \-h, \-\-help
Show summary of options
.SH BUGS
None known.
.SH AUTHOR
geni-fetch-aggmon was written by Raytheon BBN Technologies.
