<?php
//----------------------------------------------------------------------
// Copyright (c) 2011 Raytheon BBN Technologies
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and/or hardware specification (the "Work") to
// deal in the Work without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Work, and to permit persons to whom the Work
// is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Work.
//
// THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS
// IN THE WORK.
//----------------------------------------------------------------------
?>
<?php
//--------------------------------------------------
// Site settings for GENI Identity Portal
//--------------------------------------------------

// Administrative email address. Used for new account registration,
// for instance.
$portal_admin_email = 'portal-dev-admin@gpolab.bbn.com';

// Where to find the gcf installation. This is necessary for
// generation of slice credentials.
$portal_gcf_dir = '/usr/share/geni-ch/portal/gcf';

// Where to find the local gcf configuration directory.
$portal_gcf_cfg_dir = '/usr/share/geni-ch/portal/gcf.d';

// Set to true for demo situations to auto approve new accounts.
$portal_auto_approve = false;

//----------------------------------------------------------------------
// Set error level to include user errors (generated by the portal).
//----------------------------------------------------------------------
// Add E_USER_ERROR to the current set
error_reporting(error_reporting() | E_USER_ERROR);

?>