//----------------------------------------------------------------------
// Copyright (c) 2012-2014 Raytheon BBN Technologies
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and/or hardware specification (the "Work") to
// deal in the Work without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Work, and to permit persons to whom the Work
// is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Work.
//
// THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS
// IN THE WORK.
//----------------------------------------------------------------------

var GENI_CONFIGURING = "<?php echo STATUS_INDEX::GENI_CONFIGURING ?>";
var GENI_READY = "<?php echo STATUS_INDEX::GENI_READY ?>";
var GENI_FAILED = "<?php echo STATUS_INDEX::GENI_FAILED ?>";
var GENI_UNKNOWN = "<?php echo STATUS_INDEX::GENI_UNKNOWN ?>";
var GENI_NO_RESOURCES = "<?php echo STATUS_INDEX::GENI_NO_RESOURCES ?>";
var GENI_BUSY = "<?php echo STATUS_INDEX::GENI_BUSY ?>";
var GENI_NO_STATUS = "<?php echo STATUS_INDEX::GENI_NO_STATUS ?>";

var GENI_CONFIGURING_STR = "<?php echo STATUS_MSG::GENI_CONFIGURING ?>";
var GENI_READY_STR = "<?php echo STATUS_MSG::GENI_READY ?>";
var GENI_FAILED_STR = "<?php echo STATUS_MSG::GENI_FAILED ?>";
var GENI_UNKNOWN_STR = "<?php echo STATUS_MSG::GENI_UNKNOWN ?>";
var GENI_NO_RESOURCES_STR = "<?php echo STATUS_MSG::GENI_NO_RESOURCES ?>";
var GENI_BUSY_STR = "<?php echo STATUS_MSG::GENI_BUSY ?>";
var GENI_NO_STATUS_STR = "<?php echo STATUS_MSG::GENI_NO_STATUS ?>";

var GENI_CONFIGURING_CLASS = "<?php echo STATUS_CLASS::GENI_CONFIGURING ?>";
var GENI_READY_CLASS = "<?php echo STATUS_CLASS::GENI_READY ?>";
var GENI_FAILED_CLASS = "<?php echo STATUS_CLASS::GENI_FAILED ?>";
var GENI_UNKNOWN_CLASS = "<?php echo STATUS_CLASS::GENI_UNKNOWN ?>";
var GENI_NO_RESOURCES_CLASS = "<?php echo STATUS_CLASS::GENI_NO_RESOURCES ?>";
var GENI_BUSY_CLASS = "<?php echo STATUS_CLASS::GENI_BUSY ?>";
var GENI_NO_STATUS_CLASS = "<?php echo STATUS_CLASS::GENI_NO_STATUS ?>";

var GENI_MESSAGES;
GENI_MESSAGES = Array();
GENI_MESSAGES[ GENI_CONFIGURING ] = GENI_CONFIGURING_STR;
GENI_MESSAGES[ GENI_READY ] = GENI_READY_STR;
GENI_MESSAGES[ GENI_FAILED ] = GENI_FAILED_STR;
GENI_MESSAGES[ GENI_UNKNOWN ] = GENI_UNKNOWN_STR;
GENI_MESSAGES[ GENI_NO_RESOURCES ] = GENI_NO_RESOURCES_STR;
GENI_MESSAGES[ GENI_BUSY ] = GENI_BUSY_STR;
GENI_MESSAGES[ GENI_NO_STATUS ] = GENI_NO_STATUS_STR;

var GENI_MESSAGES_REV;
GENI_MESSAGES_REV = Array();
GENI_MESSAGES_REV[ GENI_CONFIGURING_STR ] = GENI_CONFIGURING;
GENI_MESSAGES_REV[ GENI_READY_STR ] = GENI_READY;
GENI_MESSAGES_REV[ GENI_FAILED_STR ] = GENI_FAILED;
GENI_MESSAGES_REV[ GENI_UNKNOWN_STR ] = GENI_UNKNOWN;
GENI_MESSAGES_REV[ GENI_NO_RESOURCES_STR ] = GENI_NO_RESOURCES;
GENI_MESSAGES_REV[ GENI_BUSY_STR ] = GENI_BUSY;
GENI_MESSAGES_REV[ GENI_NO_STATUS_STR ] = GENI_NO_STATUS;

var GENI_CLASSES;
GENI_CLASSES = Array();
GENI_CLASSES[ GENI_CONFIGURING ] = GENI_CONFIGURING_CLASS;
GENI_CLASSES[ GENI_READY ] = GENI_READY_CLASS;
GENI_CLASSES[ GENI_FAILED ] = GENI_FAILED_CLASS;
GENI_CLASSES[ GENI_UNKNOWN ] = GENI_UNKNOWN_CLASS;
GENI_CLASSES[ GENI_NO_RESOURCES ] = GENI_NO_RESOURCES_CLASS;
GENI_CLASSES[ GENI_BUSY ] = GENI_BUSY_CLASS;
GENI_CLASSES[ GENI_NO_STATUS ] = GENI_NO_STATUS_CLASS;
