update cs_action
set privilege = privilege - 100 
where 
privilege > 0 and
name in ('create_assertion', 
      'create_policy'
      'create_assertion',
      'create_policy',
      'renew_assertion',
      'delete_policy',
--      'query_assertions',
--      'query_policies',
--      'lookup_slice',
--      'lookup_slices',
--      'lookup_slice_ids',
--      'get_slice_credential',
--      'add_slivers',
--      'delete_slivers',
      'renew_slice',
--      'get_slice_members',
--      'get_slices_for_member',
--      'lookup_slices_by_ids',
--      'get_slice_members_for_project',
--      'list_resources',
--      'get_services',
--      'get_services_of_type',
      'register_service',
      'remove_service',
      'create_project',
      'delete_project',
--      'get_projects',
--      'get_project_by_lead',
--      'lookup_project',
--      'update_project',
--      'get_project_members',
--      'get_projects_for_member',
      'administer_resources',
      'administer_services',
      'administer_members',
      'change_lead',
      'add_project_member',
      'remove_project_member',
      'change_member_role',
      'remove_slice_member',
      'add_slice_member',
      'change_slice_member_role',
      'create_slice',
      'invite_member',
      'modify_slice_membership',
      'modify_project_membership');
