\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename geni-portal.info
@settitle GENI Portal Manual 2.29
@c %**end of header

@copying
Copyright @copyright{} 2015 Raytheon BBN Technologies

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and/or hardware specification (the "Work") to
deal in the Work without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Work, and to permit persons to whom the Work
is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Work.

THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS
IN THE WORK.
@end copying

@titlepage
@title The GENI Portal
@subtitle Version 2.29, March, 2015
@author Marshall Brinn
@author Aaron Helsinger
@author Tom Mitchell
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top GENI Portal

@insertcopying
@end ifnottex

@menu
* First Chapter::    The first chapter is the
                      only chapter in this sample.
* Installation::     Installation guide for CentOS 6.5.
* Index::            Complete index.
@end menu


@node First Chapter
@chapter First Chapter

@cindex chapter, first

This is the first chapter.
@cindex index entry, another

Here is a numbered list.

@enumerate
@item
This is the first item.

@item
This is the second item.
@end enumerate


@node Installation
@chapter Installation

This chapter describes installing the GENI Portal and Clearinghouse on
CentOS 6.5.

@section Prepare the host

@subsection Disable SELinux
The GENI Portal and Clearinghouse are not compatible with SELinux, so
it must be disabled. To test for SELinux, use the @command{sestatus}
command.

@example
$ sestatus
SELinux status:                 disabled
@end example

@noindent
If SELinux is enabled, google ``CentOS disable SELinux'' for
instructions. Do not proceed until SELinux has been disabled.

@subsection Disable Firewall

@emph{N.B. This should not be necessary and this step should be fixed.}

Disable iptables during installation. Check for the minimum ports
later in the document.

@example
sudo service iptables stop
@end example

@section Install Shibboleth

@emph{This section will be filled in later.}

@section Install GENI Portal

@emph{This section will be filled in later.}

@section Install GENI Clearinghouse

@subsection Install ABAC

@example
cd /usr/share/geni-ch
sudo bash
wget abac.deterlab.net/src/abac-0.1.7.tar.gz
ln -s /usr/lib64/libltdl.so.7.2.1 /usr/lib64/libltdl.so
tar xvzf abac-0.1.7.tar.gz
ln -s abac-0.1.7 abac
cd abac
./configure --prefix=/usr --sysconfdir=/etc --bindir=/usr/local/bin \
        --sbindir=/usr/local/sbin PYTHON_VERSION='2.7' \
        --with-site-perl=/usr/local/share/perl5
make
make install
ln -s /usr/lib/python2.7/site-packages/_ABAC.* \
        /usr/local/lib/python2.7/site-packages/
exit
@end example

@subsection Install AMSoil

Get AMsoil tar ball

@emph{N.B. Need to change to a publicly available URL or alter the
 download instructions.}

@example
cd /tmp
wget http://www.gpolab.bbn.com/internal/projects/chapi/AMsoil-gpo-0.3.2.tar.gz
@end example

@subsection Install chapi

@example
cd chapi/tools
touch ../etc/geni-chapi-githash
install-chapi-centos.sh
@end example

@node Index
@unnumbered Index

@printindex cp

@bye